# Configuração de Guardrails por Agente - Cliente Genérico
# Define quais guardrails cada agente deve usar

# Mapeamento de agentes para guardrails - APENAS IA
Triage Agent:
  - validate_content_with_ai

Flow Agent:
  - validate_content_with_ai

Interview Agent:
  - validate_content_with_ai

Answer Agent:
  - validate_content_with_ai

Confirmation Agent:
  - validate_content_with_ai

Knowledge Agent:
  - validate_content_with_ai

Usage Agent:
  - validate_content_with_ai
