# Configuração de Guardrails para EasyDr
# Específico para domínio médico e saúde

# Palavras sensíveis específicas do domínio médico
sensitive_words:
  # Segurança geral
  - "password"
  - "senha" 
  - "token"
  - "key"
  - "secret"
  - "hack"
  - "exploit"
  - "malware"
  - "virus"
  
  # Domínio específico - Médico/Saúde
  - "overdose"
  - "suicídio"
  - "eutanásia"
  - "aborto"
  - "drogas"
  - "medicamento_controlado"
  - "prescrição_falsa"
  
  # Palavras ofensivas
  - "idiota"
  - "burro"
  - "estúpido"
  - "imbecil"

# Tópicos permitidos (relacionados ao negócio da EasyDr)
on_topic_keywords:
  # Domínio principal - Saúde e Medicina
  - "saúde"
  - "medicina"
  - "médico"
  - "médica"
  - "doutor"
  - "doutora"
  - "paciente"
  - "consulta"
  - "exame"
  - "diagnóstico"
  - "tratamento"
  - "medicamento"
  - "remédio"
  - "receita"
  - "prescrição"
  - "sintoma"
  - "doença"
  - "patologia"
  - "cirurgia"
  - "procedimento"
  - "hospital"
  - "clínica"
  - "laboratório"
  - "ambulatório"
  - "emergência"
  - "urgência"
  - "pronto socorro"
  - "ps"
  - "uti"
  - "enfermaria"
  - "enfermeiro"
  - "enfermeira"
  - "técnico"
  - "técnica"
  - "auxiliar"
  - "fisioterapeuta"
  - "psicólogo"
  - "psicóloga"
  - "nutricionista"
  - "farmacêutico"
  - "farmacêutica"
  
  # Especialidades médicas
  - "cardiologia"
  - "cardiologista"
  - "neurologia"
  - "neurologista"
  - "pediatria"
  - "pediatra"
  - "ginecologia"
  - "ginecologista"
  - "obstetrícia"
  - "obstetra"
  - "ortopedia"
  - "ortopedista"
  - "dermatologia"
  - "dermatologista"
  - "oftalmologia"
  - "oftalmologista"
  - "otorrinolaringologia"
  - "otorrino"
  - "psiquiatria"
  - "psiquiatra"
  - "endocrinologia"
  - "endocrinologista"
  - "gastroenterologia"
  - "gastroenterologista"
  - "urologia"
  - "urologista"
  - "oncologia"
  - "oncologista"
  - "radiologia"
  - "radiologista"
  - "anestesiologia"
  - "anestesiologista"
  
  # Sistemas e órgãos
  - "coração"
  - "pulmão"
  - "fígado"
  - "rim"
  - "cérebro"
  - "sistema nervoso"
  - "sistema cardiovascular"
  - "sistema respiratório"
  - "sistema digestivo"
  - "sistema urinário"
  - "sistema reprodutor"
  - "sistema endócrino"
  - "sistema imunológico"
  - "sangue"
  - "pressão arterial"
  - "glicemia"
  - "colesterol"
  - "hemoglobina"
  - "leucócitos"
  - "plaquetas"
  
  # Exames e procedimentos
  - "exame de sangue"
  - "hemograma"
  - "raio x"
  - "tomografia"
  - "ressonância"
  - "ultrassom"
  - "ecocardiograma"
  - "eletrocardiograma"
  - "ecg"
  - "endoscopia"
  - "colonoscopia"
  - "biópsia"
  - "cirurgia"
  - "anestesia"
  - "sutura"
  - "curativo"
  - "vacina"
  - "vacinação"
  - "imunização"
  
  # Medicamentos e tratamentos
  - "antibiótico"
  - "analgésico"
  - "anti-inflamatório"
  - "antitérmico"
  - "antialérgico"
  - "antidepressivo"
  - "ansiolítico"
  - "quimioterapia"
  - "radioterapia"
  - "fisioterapia"
  - "terapia"
  - "reabilitação"
  - "prevenção"
  - "profilaxia"
  
  # Códigos e classificações
  - "cid"
  - "tuss"
  - "cbhpm"
  - "amb"
  - "sus"
  - "ans"
  - "conselho federal"
  - "crm"
  - "cfm"
  - "coren"
  - "crf"
  
  # EasyDr específico
  - "easydr"
  - "easy dr"
  - "easy"
  - "dr"
  - "agendamento"
  - "marcação"
  - "horário"
  - "disponibilidade"
  - "calendário"
  - "agenda"
  - "telemedicina"
  - "consulta online"
  - "consulta remota"
  - "teleconsulta"
  
  # Termos administrativos
  - "convênio"
  - "plano de saúde"
  - "particular"
  - "público"
  - "sus"
  - "ans"
  - "reembolso"
  - "coparticipação"
  - "franquia"
  - "carência"
  - "autorização"
  - "prestador"
  - "credenciado"
  
  # Sintomas e condições
  - "dor"
  - "febre"
  - "tosse"
  - "falta de ar"
  - "nausea"
  - "vômito"
  - "diarreia"
  - "constipação"
  - "cansaço"
  - "fadiga"
  - "tontura"
  - "desmaio"
  - "convulsão"
  - "crise"
  - "ataque"
  - "infarto"
  - "avc"
  - "derrame"
  - "câncer"
  - "tumor"
  - "metástase"
  - "remissão"
  
  # Idades e grupos
  - "bebê"
  - "criança"
  - "adolescente"
  - "adulto"
  - "idoso"
  - "gestante"
  - "grávida"
  - "puérpera"
  - "recém-nascido"
  - "neonato"
  - "prematuro"
  
  # Emergências
  - "emergência"
  - "urgência"
  - "pronto socorro"
  - "samu"
  - "ambulância"
  - "resgate"
  - "primeiros socorros"
  - "reanimação"
  - "cpr"
  - "massagem cardíaca"
  - "respiração boca a boca"

# Padrões suspeitos de código malicioso
suspicious_patterns:
  - "delete\\s+.*"
  - "drop\\s+.*"
  - "exec\\s+.*"
  - "eval\\s+.*"
  - "system\\s+.*"

# Códigos médicos válidos (EasyDr)
valid_codes:
  - "CID10"
  - "CID11"
  - "TUSS"
  - "CBHPM"
  - "AMB"
  - "SUS"

# Configurações de spam
min_message_length: 5

spam_patterns:
  - "(.)\\1{4,}"  # Repetição excessiva de caracteres
  - "^[0-9]+$"    # Apenas números
