# Configuração de Guardrails Especializados - Cliente Genérico
# Sistema ultra-simplificado usando apenas descrições de agentes
# Toda validação é feita pela IA baseada na descrição

# Descrições de escopo para cada agente
agent_scope_descriptions:
  Triage Agent:
    description: "Agente de triagem que roteia conversas para agentes especializados. Deve aceitar qualquer pergunta relacionada aos serviços da empresa."
    
  Flow Agent:
    description: "Agente de fluxo que identifica tópicos específicos do negócio. Deve aceitar perguntas sobre identificação de fluxos e processos empresariais."
    
  Interview Agent:
    description: "Agente de entrevista que coleta informações detalhadas. Deve aceitar perguntas sobre coleta de dados e informações do cliente."
    
  Answer Agent:
    description: "Agente de resposta que fornece informações e soluções. Deve aceitar perguntas sobre respostas, soluções e orientações técnicas."
    
  Confirmation Agent:
    description: "Agente de confirmação que valida informações. Deve aceitar perguntas sobre confirmação e validação de dados e processos."
    
  Knowledge Agent:
    description: "Agente de conhecimento que consulta documentação. Deve aceitar perguntas sobre consulta de documentação e base de conhecimento."
    
  Usage Agent:
    description: "Agente de uso que explica funcionalidades do sistema. Deve aceitar perguntas sobre como usar o sistema e orientações de navegação."