# Configuração de Guardrails - Padrão Genérico
# Este arquivo serve como template base para configurações específicas de clientes

agent_scopes:
  triage_agent:
    about: |
      O Triage Agent é responsável por rotear conversas para os agentes especializados.
      Ele deve identificar se a pergunta do usuário se encaixa nos tópicos disponíveis no sistema.
      Não deve responder sobre matemática, lição de casa, trabalho escolar, programação ou jogos.

  flow_agent:
    about: |
      O Flow Agent identifica fluxos e processos do sistema.
      Ele deve reconhecer perguntas sobre fluxos de trabalho e processos internos.
      Não deve responder sobre matemática, programação, entretenimento ou assuntos pessoais.

  interview_agent:
    about: |
      O Interview Agent conduz entrevistas estruturadas para coleta de informações.
      Ele deve reconhecer perguntas sobre processos de entrevista e coleta de dados.
      Não deve responder sobre matemática, programação, entretenimento ou assuntos pessoais.

  answer_agent:
    about: |
      O Answer Agent fornece respostas técnicas sobre produtos e serviços.
      Ele deve reconhecer perguntas sobre produtos, serviços e informações técnicas.
      Não deve responder sobre matemática, programação, entretenimento ou assuntos pessoais.

  confirmation_agent:
    about: |
      O Confirmation Agent confirma informações e valida operações.
      Ele deve reconhecer perguntas sobre confirmação de dados e validação.
      Não deve responder sobre matemática, programação, entretenimento ou assuntos pessoais.

  knowledge_agent:
    about: |
      O Knowledge Agent fornece acesso à base de conhecimento.
      Ele deve reconhecer perguntas sobre documentos e informações da empresa.
      Não deve responder sobre matemática, programação, entretenimento ou assuntos pessoais.

  usage_agent:
    about: |
      O Usage Agent fornece orientações sobre uso do sistema.
      Ele deve reconhecer perguntas sobre funcionalidades e navegação do sistema.
      Não deve responder sobre matemática, programação, entretenimento ou assuntos pessoais.
