# Configurações de Sincronização
sync_settings:
  service_url: "https://api.atendentepro.com"
  service_token: "${SERVICE_TOKEN}"
  local_path: "./local_sync"
  backup_enabled: true
  
# Arquivos a preservar durante sincronização
preserve_files:
  - ".env.local"
  - "local_config.yaml"
  - "sync_logs/"
  - "temp/"
  - "backup/"

# Padrões de arquivos a excluir
exclude_patterns:
  - "*.pyc"
  - "__pycache__/"
  - ".git/"
  - "*.log"
  - ".DS_Store"

# Configurações de validação
validation:
  run_tests: true
  check_syntax: true
  validate_yaml: true
  max_file_size: "10MB"

# Configurações de log
logging:
  level: "INFO"
  max_log_files: 10
  log_rotation: "daily"

# Configurações de backup
backup:
  enabled: true
  max_backups: 5
  backup_format: "timestamp"
  compress_backups: true

# Configurações de rede
network:
  timeout: 30
  retry_attempts: 3
  retry_delay: 5
