# Configuração de Guardrails por Agente - White Martins
# Define quais guardrails cada agente deve usar e seus temas específicos

# Mapeamento de agentes para guardrails
Triage Agent:
  guardrails:
    - reject_off_topic_queries
    - detect_spam_patterns
  on_topic_keywords:
    # Triage - entrada geral, aceita qualquer tema relacionado ao negócio
    - "iva"
    - "código"
    - "códigos"
    - "tributário"
    - "tributação"
    - "imposto"
    - "impostos"
    - "fiscal"
    - "fiscalização"
    - "nota fiscal"
    - "nf"
    - "nfe"
    - "nfce"
    - "icms"
    - "ipi"
    - "pis"
    - "cofins"
    - "simples nacional"
    - "microempresa"
    - "substituição tributária"
    - "st"
    - "compra"
    - "compras"
    - "industrialização"
    - "industrial"
    - "produção"
    - "manufaturado"
    - "comercialização"
    - "comercial"
    - "revenda"
    - "ativo operacional"
    - "ativo projeto"
    - "máquina"
    - "equipamento"
    - "cilindro"
    - "consumo administrativo"
    - "administrativo"
    - "escritório"
    - "limpeza"
    - "ti"
    - "frete"
    - "transporte"
    - "logística"
    - "energia elétrica"
    - "energia"
    - "elétrica"
    - "eletricidade"
    - "serviço operação"
    - "serviço não operação"
    - "manutenção"
    - "assistência"
    - "engenharia"
    - "consultoria"
    - "auditoria"
    - "inspeção"
    - "fornecedor"
    - "fornecedores"
    - "cliente"
    - "clientes"
    - "empresa"
    - "empresas"
    - "cnpj"
    - "cpf"
    - "pessoa física"
    - "pessoa jurídica"
    - "processo"
    - "procedimento"
    - "documentação"
    - "documento"
    - "documentos"
    - "análise"
    - "análises"
    - "consulta"
    - "consultas"
    - "orientação"
    - "orientações"
    - "suporte"
    - "atendimento"
    - "ajuda"
    - "white martins"
    - "white"
    - "martins"
    - "gás"
    - "gases"
    - "oxigênio"
    - "nitrogênio"
    - "argônio"
    - "hidrogênio"
    - "hélio"
    - "acetileno"
    - "co2"
    - "dióxido de carbono"
    - "soldagem"
    - "corte"
    - "laboratório"
    - "hospitalar"
    - "alimentício"
    - "bebida"
    - "refrigeração"
    - "ar condicionado"
    - "caldeira"
    - "forno"
    - "queima"
    - "combustão"
    - "confirmar"
    - "validação"
    - "conferência"
    - "revisar solicitação"
    - "procedimento"
    - "norma"
    - "usar o sistema"
    - "como funciona"
    - "ajuda plataforma"
    - "suporte ferramenta"

Flow Agent:
  guardrails:
    - reject_off_topic_queries
  on_topic_keywords:
    # Flow - identifica tópicos específicos de IVA
    - "iva"
    - "duvida iva"
    - "duvida sobre iva"
    - "qual iva"
    - "código"
    - "códigos"
    - "tributário"
    - "tributação"
    - "imposto"
    - "impostos"
    - "fiscal"
    - "fiscalização"
    - "nota fiscal"
    - "nf"
    - "nfe"
    - "nfce"
    - "icms"
    - "ipi"
    - "pis"
    - "cofins"
    - "simples nacional"
    - "microempresa"
    - "substituição tributária"
    - "st"
    - "compra"
    - "compras"
    - "industrialização"
    - "industrial"
    - "produção"
    - "manufaturado"
    - "comercialização"
    - "comercial"
    - "revenda"
    - "ativo operacional"
    - "ativo projeto"
    - "máquina"
    - "equipamento"
    - "cilindro"
    - "consumo administrativo"
    - "administrativo"
    - "escritório"
    - "limpeza"
    - "ti"
    - "frete"
    - "transporte"
    - "logística"
    - "energia elétrica"
    - "energia"
    - "elétrica"
    - "eletricidade"
    - "serviço operação"
    - "serviço não operação"
    - "manutenção"
    - "assistência"
    - "engenharia"
    - "consultoria"
    - "auditoria"
    - "inspeção"

Interview Agent:
  guardrails:
    - reject_sensitive_content
  on_topic_keywords:
    # Interview - coleta informações sobre tópicos já identificados
    - "iva"
    - "código"
    - "códigos"
    - "tributário"
    - "tributação"
    - "imposto"
    - "impostos"
    - "fiscal"
    - "fiscalização"
    - "nota fiscal"
    - "nf"
    - "nfe"
    - "nfce"
    - "icms"
    - "ipi"
    - "pis"
    - "cofins"
    - "simples nacional"
    - "microempresa"
    - "substituição tributária"
    - "st"
    - "compra"
    - "compras"
    - "industrialização"
    - "industrial"
    - "produção"
    - "manufaturado"
    - "comercialização"
    - "comercial"
    - "revenda"
    - "ativo operacional"
    - "ativo projeto"
    - "máquina"
    - "equipamento"
    - "cilindro"
    - "consumo administrativo"
    - "administrativo"
    - "escritório"
    - "limpeza"
    - "ti"
    - "frete"
    - "transporte"
    - "logística"
    - "energia elétrica"
    - "energia"
    - "elétrica"
    - "eletricidade"
    - "serviço operação"
    - "serviço não operação"
    - "manutenção"
    - "assistência"
    - "engenharia"
    - "consultoria"
    - "auditoria"
    - "inspeção"
    - "fornecedor"
    - "fornecedores"
    - "cliente"
    - "clientes"
    - "empresa"
    - "empresas"
    - "cnpj"
    - "cpf"
    - "pessoa física"
    - "pessoa jurídica"

Answer Agent:
  guardrails:
    - reject_sensitive_content
    - validate_topic_and_codes # Only Answer Agent has this now
  on_topic_keywords:
    # Answer - fornece respostas finais sobre IVA
    - "iva"
    - "código"
    - "códigos"
    - "tributário"
    - "tributação"
    - "imposto"
    - "impostos"
    - "fiscal"
    - "fiscalização"
    - "nota fiscal"
    - "nf"
    - "nfe"
    - "nfce"
    - "icms"
    - "ipi"
    - "pis"
    - "cofins"
    - "simples nacional"
    - "microempresa"
    - "substituição tributária"
    - "st"
    - "compra"
    - "compras"
    - "industrialização"
    - "industrial"
    - "produção"
    - "manufaturado"
    - "comercialização"
    - "comercial"
    - "revenda"
    - "ativo operacional"
    - "ativo projeto"
    - "máquina"
    - "equipamento"
    - "cilindro"
    - "consumo administrativo"
    - "administrativo"
    - "escritório"
    - "limpeza"
    - "ti"
    - "frete"
    - "transporte"
    - "logística"
    - "energia elétrica"
    - "energia"
    - "elétrica"
    - "eletricidade"
    - "serviço operação"
    - "serviço não operação"
    - "manutenção"
    - "assistência"
    - "engenharia"
    - "consultoria"
    - "auditoria"
    - "inspeção"

Confirmation Agent:
  guardrails:
    - reject_sensitive_content
  on_topic_keywords:
    # Confirmation - confirma códigos IVA específicos
    - "confirmar"
    - "validação"
    - "conferência"
    - "revisar solicitação"
    - "iva"
    - "código"
    - "códigos"
    - "tributário"
    - "tributação"
    - "imposto"
    - "impostos"
    - "fiscal"
    - "fiscalização"
    - "nota fiscal"
    - "nf"
    - "nfe"
    - "nfce"
    - "icms"
    - "ipi"
    - "pis"
    - "cofins"
    - "simples nacional"
    - "microempresa"
    - "substituição tributária"
    - "st"
    - "cd"
    - "f0"
    - "f1"
    - "f3"
    - "f5"
    - "fe"
    - "fd"
    - "fa"
    - "fc"
    - "fb"
    - "f2"
    - "f7"
    - "f4"
    - "transferência"
    - "isento"
    - "tributação"

Knowledge Agent:
  guardrails:
    - reject_off_topic_queries
    - detect_spam_patterns
  on_topic_keywords:
    # Knowledge - responde sobre procedimentos e documentação
    - "procedimento"
    - "documentação"
    - "dúvidas gerais"
    - "norma"
    - "determinação iva"
    - "finalidade compra"
    - "aquisição"
    - "carta de correção"
    - "cancelamento extemporâneo"
    - "manifestação destinatário"
    - "recebimento notas fiscais"
    - "processo"
    - "documento"
    - "documentos"
    - "metadado"
    - "referência"
    - "origem"
    - "página"
    - "sistema ask"
    - "nf-e"
    - "ct-e"
    - "mdf-e"
    - "cc-e"
    - "peso"
    - "descrição"
    - "cfop"
    - "dados cadastrais"
    - "valores"
    - "alíquotas"
    - "cálculo impostos"
    - "fato gerador"
    - "prazo legal"
    - "transmissão eletrônica"
    - "nota estorno"
    - "processo administrativo"
    - "comprovantes"
    - "anexos"

Usage Agent:
  guardrails:
    - detect_spam_patterns
  on_topic_keywords:
    # Usage - responde sobre uso do sistema
    - "usar o sistema"
    - "como funciona"
    - "ajuda plataforma"
    - "suporte ferramenta"
    - "sistema"
    - "plataforma"
    - "ferramenta"
    - "uso"
    - "funcionamento"
    - "ajuda"
    - "suporte"
    - "tutorial"
    - "guia"
    - "manual"
    - "instruções"
    - "como usar"
    - "como funciona"
    - "como fazer"
    - "como configurar"
    - "como acessar"
    - "como navegar"
    - "funcionalidades"
    - "recursos"
    - "capacidades"
    - "limitações"
    - "restrições"