topics:
  compra_industrializacao:
    description: "Compra para industrialização — material manufaturado ou processo produtivo"
    codes:
      - I0
      - ID
      - IE
      - I8
      - I5
      - I9
      - I2
      - I7
      - I1
      - I3
      - I4
  compra_comercializacao:
    description: "Compra para comercialização — produto para revenda sem alteração"
    codes:
      - R0
      - ID
      - R6
      - R1
      - R5
      - R3
      - R2
      - R4
  compra_ativo_operacional:
    description: "Compra de ativo operacional — máquinas, equipamentos, cilindros (CIAP imediato)"
    codes:
      - C0
      - C6
      - CA
      - CI
      - CB
      - CD
  compra_ativo_projeto:
    description: "Compra de ativo de projeto — ativos em andamento (CIAP após conclusão)"
    codes:
      - C0
      - C6
      - CE
      - CH
      - CF
      - CG
  consumo_administrativo_ativo_nao_operacional:
    description: "Consumo administrativo e ativo não operacional — escritório, limpeza, mesas, TI"
    codes:
      - C0
      - C6
      - C1
      - C5
      - C3
      - C8
      - C9
  aquisicao_frete:
    description: "Aquisição de frete — serviços de transporte"
    codes:
      - F0
      - F1
      - F5
      - FE
      - FA
      - F2
      - FC
      - F7
      - F3
      - FD
      - FB
      - F4
  aquisicao_energia_eletrica:
    description: "Aquisição de energia elétrica — produtiva vs administrativa"
    codes:
      - E1
      - E2
      - E3
      - E4
      - E0
  aquisicao_servicos_ligados_a_operacao:
    description: "Aquisição de serviços ligados à operação — manutenção, assistência técnica, engenharia"
    codes:
      - YE
      - YH
      - YC
      - YB
  aquisicao_servicos_nao_ligados_a_operacao:
    description: "Aquisição de serviços não ligados à operação — consultorias, auditorias, inspeções"
    codes:
      - YD
      - YA
      - YG
      - YF

answer_template: |
  1. **Compra para Industrialização** — material manufaturado ou processo produtivo
     - **Definição:** itens transformados ou utilizados diretamente na produção.
     - **Códigos IVA:**
       • **I0** - Importação
       • **ID** - Fornecedor microempresa optante pelo Simples Nacional
       • **IE** - Fornecedor não Simples Nacional sem tributação
       • **I8** - Fornecedor não Simples Nacional com apenas ICMS
       • **I5** - Fornecedor não Simples Nacional com apenas IPI
       • **I9** - Fornecedor não Simples Nacional com ICMS + IPI
       • **I2** - Fornecedor não Simples Nacional com ICMS + ST (Substituição Tributária)
       • **I7** - Fornecedor não Simples Nacional com ICMS + IPI + ST
       • **I1, I3, I4** - Fornecedor beneficiado sem incidência de PIS/Cofins

  2. **Compra para Comercialização** — produto para revenda sem alteração
     - **Definição:** mercadorias revendidas tal como foram recebidas.
     - **Códigos IVA:**
       • **R0** - Importação
       • **ID** - Fornecedor microempresa optante pelo Simples Nacional
       • **R6** - Fornecedor não Simples Nacional sem tributação
       • **R1** - Fornecedor não Simples Nacional com apenas ICMS
       • **R5** - Fornecedor não Simples Nacional com apenas IPI
       • **R3** - Fornecedor não Simples Nacional com ICMS + IPI
       • **R2** - Fornecedor não Simples Nacional com ICMS + ST (Substituição Tributária)
       • **R4** - Fornecedor não Simples Nacional com ICMS + IPI + ST

  3. **Compra de Ativo Operacional** — CIAP imediato
     - **Definição:** máquinas, equipamentos, cilindros e itens diretamente ligados à operação.
     - **Códigos IVA:**
       • **C0** - Importação
       • **C6** - Fornecedor microempresa optante pelo Simples Nacional
       • **CA** - Fornecedor não Simples Nacional com apenas ICMS
       • **CI** - Fornecedor não Simples Nacional com ICMS + IPI
       • **CB** - Fornecedor não Simples Nacional com ICMS + ST (Substituição Tributária)
       • **CD** - Fornecedor não Simples Nacional com ICMS + IPI + ST

  4. **Compra de Ativo de Projeto** — uso após conclusão
     - **Definição:** ativos que só entram em operação após finalização do projeto.
     - **Códigos IVA:**
       • **C0** - Importação
       • **C6** - Fornecedor microempresa optante pelo Simples Nacional
       • **CE** - Fornecedor não Simples Nacional com apenas ICMS
       • **CH** - Fornecedor não Simples Nacional com ICMS + IPI
       • **CF** - Fornecedor não Simples Nacional com ICMS + ST (Substituição Tributária)
       • **CG** - Fornecedor não Simples Nacional com ICMS + IPI + ST

  5. **Consumo Administrativo / Ativo Não Operacional**
     - **Definição:** materiais e ativos sem vínculo direto com produção (escritório, limpeza, TI).
     - **Códigos IVA:**
       • **C0** - Importação ou sem tributação
       • **C6** - Fornecedor microempresa optante pelo Simples Nacional
       • **C1** - Fornecedor não Simples Nacional com apenas ICMS
       • **C5** - Fornecedor não Simples Nacional com apenas IPI
       • **C3** - Fornecedor não Simples Nacional com ICMS + IPI
       • **C8** - Fornecedor não Simples Nacional com ICMS + ST (Substituição Tributária)
       • **C9** - Fornecedor não Simples Nacional com ICMS + IPI + ST

  6. **Aquisição de Frete** — serviços de transporte
     - **Definição:** fretes associados a industrialização, revenda, ativos ou consumo.
     - **Códigos IVA por operação:**
       
       **Industrialização/Revenda:**
       • **F0** - Sem tributação
       • **F1** - Apenas ICMS
       • **F5** - Isento de ICMS
       • **FE** - Isento de ICMS + ST
       • **FA** - ICMS + ST
       • **F2** - Operação de transferência
       
       **Ativo Operacional:**
       • **F0** - Sem tributação
       • **F1** - Apenas ICMS
       • **F5** - Isento de ICMS
       • **FA** - ICMS + ST
       • **F2** - Operação de transferência
       
       **Ativo Operacional Projeto:**
       • **F0** - Sem tributação
       • **F1** - Apenas ICMS
       • **F5** - Isento de ICMS
       • **FC** - ICMS + ST
       • **F7** - Operação de transferência
       
       **Ativo Não Operacional/Consumo:**
       • **F0** - Sem tributação
       • **F3** - Apenas ICMS
       • **F5** - Isento de ICMS
       • **FD** - Isento de ICMS + ST
       • **FB** - ICMS + ST
       • **F4** - Operação de transferência

  7. **Aquisição de Energia Elétrica** — produção vs consumo administrativo
     - **Definição:** energia com ou sem crédito de ICMS/PIS/COFINS.
     - **Códigos IVA:**
       • **E1** - Energia para produção (com crédito de ICMS/PIS/COFINS)
       • **E2** - Energia para produção (com crédito parcial de ICMS/PIS/COFINS)
       • **E3** - Energia para produção (sem crédito de ICMS/PIS/COFINS)
       • **E4** - Energia para consumo administrativo (sem crédito)
       • **E0** - Energia mista (produção + administrativo - usar duas linhas)
       
       **IMPORTANTE:** Para energia mista, criar duas linhas no pedido com valores e IVAs correspondentes a cada finalidade, respeitando os percentuais do laudo.

  8. **Serviços Ligados à Operação** — manutenção, assistência técnica, engenharia
     - **Definição:** serviços com vínculo direto à operação produtiva.
     - **Códigos IVA (baseado em retenções):**
       • **YE** - Com retenção de ISS, sem retenção federal
       • **YH** - Com retenção de ISS + retenção federal (IRF - PCC/IR)
       • **YC** - Sem retenção de ISS, com retenção federal (IRF - PCC/IR)
       • **YB** - Sem retenção de ISS, sem retenção federal

  9. **Serviços Não Ligados à Operação** — consultorias, auditorias, inspeções
     - **Definição:** serviços administrativos ou de apoio.
     - **Códigos IVA (baseado em retenções):**
       • **YD** - Com retenção de ISS, sem retenção federal
       • **YA** - Com retenção de ISS + retenção federal (IRF - PCC/IR)
       • **YG** - Sem retenção de ISS, com retenção federal (IRF - PCC/IR)
       • **YF** - Sem retenção de ISS, sem retenção federal
                    


