# Configuração de Guardrails Especializados - White Martins
# Sistema ultra-simplificado usando descrições, escopos e tópicos de agentes
# Toda validação é feita pela IA baseada na descrição, escopo e tópicos

# Descrições e escopos para cada agente
agent_scope_descriptions:
  Triage Agent:
    description: "Agente de triagem que roteia conversas para agentes especializados. Deve aceitar qualquer pergunta relacionada a serviços da empresa, tributação, IVA, energia elétrica, compras industriais/comerciais, ativos operacionais, frete, serviços operacionais e não-operacionais."
    scope: "Tributação, IVA, energia elétrica, compras empresariais, ativos, frete, serviços da empresa"
    
  Flow Agent:
    description: "Agente de fluxo que identifica tópicos específicos de tributação e IVA. Deve aceitar perguntas sobre códigos IVA, tipos de compra (industrialização, comercialização), ativos operacionais e de projeto, consumo administrativo, frete, energia elétrica e serviços."
    scope: "Identificação de tópicos tributários, códigos IVA, tipos de compra empresarial"
    
  Interview Agent:
    description: "Agente de entrevista que coleta informações detalhadas sobre operações tributárias. Deve aceitar perguntas sobre fornecedores, tipos de operação, códigos IVA específicos, contexto de compras e operações empresariais."
    scope: "Coleta de informações sobre operações tributárias, fornecedores, códigos IVA"
    
  Answer Agent:
    description: "Agente de resposta que fornece informações detalhadas sobre tributação e IVA. Deve aceitar perguntas sobre códigos IVA, tipos de compra, ativos operacionais, consumo administrativo, frete, energia elétrica e serviços operacionais."
    scope: "Fornecimento de respostas sobre tributação, códigos IVA, tipos de compra empresarial"
    
  Confirmation Agent:
    description: "Agente de confirmação que valida informações sobre operações tributárias. Deve aceitar perguntas sobre confirmação de códigos IVA, tipos de operação, fornecedores e contexto de compras empresariais."
    scope: "Confirmação de informações tributárias, códigos IVA, operações empresariais"
    
  Knowledge Agent:
    description: "Agente de conhecimento que consulta documentação sobre tributação e IVA. Deve aceitar perguntas sobre consulta de códigos IVA, tipos de compra, ativos operacionais, consumo administrativo, frete, energia elétrica e serviços."
    scope: "Consulta de documentação tributária, códigos IVA, procedimentos empresariais"
    
  Usage Agent:
    description: "Agente de uso que explica funcionalidades do sistema de atendimento tributário. Deve aceitar perguntas sobre como usar o sistema, navegação, orientações de uso e ajuda técnica relacionada ao sistema."
    scope: "Funcionalidades do sistema, orientações de uso, navegação, ajuda técnica"

# Estrutura de tópicos e códigos IVA válidos (White Martins)
topics:
  compra_industrializacao:
    description: "Compra para industrialização — material manufaturado ou processo produtivo"
    codes:
      - "I0"  # Importação
      - "ID"  # Fornecedor microempresa optante pelo Simples Nacional
      - "IE"  # Fornecedor não Simples Nacional sem tributação
      - "I8"  # Fornecedor não Simples Nacional com apenas ICMS
      - "I5"  # Fornecedor não Simples Nacional com apenas IPI
      - "I9"  # Fornecedor não Simples Nacional com ICMS + IPI
      - "I2"  # Fornecedor não Simples Nacional com ICMS + ST (Substituição Tributária)
      - "I7"  # Fornecedor não Simples Nacional com ICMS + IPI + ST
      - "I1"  # Fornecedor beneficiado sem incidência de PIS/Cofins
      - "I3"  # Fornecedor beneficiado sem incidência de PIS/Cofins
      - "I4"  # Fornecedor beneficiado sem incidência de PIS/Cofins

  compra_comercializacao:
    description: "Compra para comercialização — revenda de produtos"
    codes:
      - "C0"  # Importação
      - "CD"  # Fornecedor microempresa optante pelo Simples Nacional
      - "CE"  # Fornecedor não Simples Nacional sem tributação
      - "C8"  # Fornecedor não Simples Nacional com apenas ICMS
      - "C5"  # Fornecedor não Simples Nacional com apenas IPI
      - "C9"  # Fornecedor não Simples Nacional com ICMS + IPI
      - "C2"  # Fornecedor não Simples Nacional com ICMS + ST
      - "C7"  # Fornecedor não Simples Nacional com ICMS + IPI + ST
      - "C1"  # Fornecedor beneficiado sem incidência de PIS/Cofins
      - "C3"  # Fornecedor beneficiado sem incidência de PIS/Cofins
      - "C4"  # Fornecedor beneficiado sem incidência de PIS/Cofins

  ativo_operacional:
    description: "Ativo operacional — equipamentos e instalações para operação"
    codes:
      - "A0"  # Importação
      - "AD"  # Fornecedor microempresa optante pelo Simples Nacional
      - "AE"  # Fornecedor não Simples Nacional sem tributação
      - "A8"  # Fornecedor não Simples Nacional com apenas ICMS
      - "A5"  # Fornecedor não Simples Nacional com apenas IPI
      - "A9"  # Fornecedor não Simples Nacional com ICMS + IPI
      - "A2"  # Fornecedor não Simples Nacional com ICMS + ST
      - "A7"  # Fornecedor não Simples Nacional com ICMS + IPI + ST
      - "A1"  # Fornecedor beneficiado sem incidência de PIS/Cofins
      - "A3"  # Fornecedor beneficiado sem incidência de PIS/Cofins
      - "A4"  # Fornecedor beneficiado sem incidência de PIS/Cofins

  ativo_projeto:
    description: "Ativo de projeto — equipamentos para projetos específicos"
    codes:
      - "P0"  # Importação
      - "PD"  # Fornecedor microempresa optante pelo Simples Nacional
      - "PE"  # Fornecedor não Simples Nacional sem tributação
      - "P8"  # Fornecedor não Simples Nacional com apenas ICMS
      - "P5"  # Fornecedor não Simples Nacional com apenas IPI
      - "P9"  # Fornecedor não Simples Nacional com ICMS + IPI
      - "P2"  # Fornecedor não Simples Nacional com ICMS + ST
      - "P7"  # Fornecedor não Simples Nacional com ICMS + IPI + ST
      - "P1"  # Fornecedor beneficiado sem incidência de PIS/Cofins
      - "P3"  # Fornecedor beneficiado sem incidência de PIS/Cofins
      - "P4"  # Fornecedor beneficiado sem incidência de PIS/Cofins

  consumo_administrativo:
    description: "Consumo administrativo — materiais para uso administrativo"
    codes:
      - "E0"  # Importação
      - "ED"  # Fornecedor microempresa optante pelo Simples Nacional
      - "EE"  # Fornecedor não Simples Nacional sem tributação
      - "E8"  # Fornecedor não Simples Nacional com apenas ICMS
      - "E5"  # Fornecedor não Simples Nacional com apenas IPI
      - "E9"  # Fornecedor não Simples Nacional com ICMS + IPI
      - "E2"  # Fornecedor não Simples Nacional com ICMS + ST
      - "E7"  # Fornecedor não Simples Nacional com ICMS + IPI + ST
      - "E1"  # Fornecedor beneficiado sem incidência de PIS/Cofins
      - "E3"  # Fornecedor beneficiado sem incidência de PIS/Cofins
      - "E4"  # Fornecedor beneficiado sem incidência de PIS/Cofins

  frete:
    description: "Frete — serviços de transporte e logística"
    codes:
      - "F0"  # Importação
      - "FD"  # Fornecedor microempresa optante pelo Simples Nacional
      - "FE"  # Fornecedor não Simples Nacional sem tributação
      - "F8"  # Fornecedor não Simples Nacional com apenas ICMS
      - "F5"  # Fornecedor não Simples Nacional com apenas IPI
      - "F9"  # Fornecedor não Simples Nacional com ICMS + IPI
      - "F2"  # Fornecedor não Simples Nacional com ICMS + ST
      - "F7"  # Fornecedor não Simples Nacional com ICMS + IPI + ST
      - "F1"  # Fornecedor beneficiado sem incidência de PIS/Cofins
      - "F3"  # Fornecedor beneficiado sem incidência de PIS/Cofins
      - "F4"  # Fornecedor beneficiado sem incidência de PIS/Cofins

  energia_eletrica:
    description: "Energia elétrica — serviços de fornecimento de energia"
    codes:
      - "Z0"  # Importação
      - "ZD"  # Fornecedor microempresa optante pelo Simples Nacional
      - "ZE"  # Fornecedor não Simples Nacional sem tributação
      - "Z8"  # Fornecedor não Simples Nacional com apenas ICMS
      - "Z5"  # Fornecedor não Simples Nacional com apenas IPI
      - "Z9"  # Fornecedor não Simples Nacional com ICMS + IPI
      - "Z2"  # Fornecedor não Simples Nacional com ICMS + ST
      - "Z7"  # Fornecedor não Simples Nacional com ICMS + IPI + ST
      - "Z1"  # Fornecedor beneficiado sem incidência de PIS/Cofins
      - "Z3"  # Fornecedor beneficiado sem incidência de PIS/Cofins
      - "Z4"  # Fornecedor beneficiado sem incidência de PIS/Cofins

  servicos_operacionais:
    description: "Serviços operacionais — serviços relacionados à operação"
    codes:
      - "S0"  # Importação
      - "SD"  # Fornecedor microempresa optante pelo Simples Nacional
      - "SE"  # Fornecedor não Simples Nacional sem tributação
      - "S8"  # Fornecedor não Simples Nacional com apenas ICMS
      - "S5"  # Fornecedor não Simples Nacional com apenas IPI
      - "S9"  # Fornecedor não Simples Nacional com ICMS + IPI
      - "S2"  # Fornecedor não Simples Nacional com ICMS + ST
      - "S7"  # Fornecedor não Simples Nacional com ICMS + IPI + ST
      - "S1"  # Fornecedor beneficiado sem incidência de PIS/Cofins
      - "S3"  # Fornecedor beneficiado sem incidência de PIS/Cofins
      - "S4"  # Fornecedor beneficiado sem incidência de PIS/Cofins

  servicos_nao_operacionais:
    description: "Serviços não-operacionais — serviços administrativos e de apoio"
    codes:
      - "N0"  # Importação
      - "ND"  # Fornecedor microempresa optante pelo Simples Nacional
      - "NE"  # Fornecedor não Simples Nacional sem tributação
      - "N8"  # Fornecedor não Simples Nacional com apenas ICMS
      - "N5"  # Fornecedor não Simples Nacional com apenas IPI
      - "N9"  # Fornecedor não Simples Nacional com ICMS + IPI
      - "N2"  # Fornecedor não Simples Nacional com ICMS + ST
      - "N7"  # Fornecedor não Simples Nacional com ICMS + IPI + ST
      - "N1"  # Fornecedor beneficiado sem incidência de PIS/Cofins
      - "N3"  # Fornecedor beneficiado sem incidência de PIS/Cofins
      - "N4"  # Fornecedor beneficiado sem incidência de PIS/Cofins