# Configuração de Guardrails - White Martins
# Este arquivo contém as configurações específicas para o sistema de guardrails

agent_scopes:
  triage_agent:
    about: |
      O Triage Agent da White Martins é responsável por identificar e direcionar 
      consultas relacionadas à determinação de códigos IVA e processos fiscais.
      Ele deve reconhecer perguntas sobre: tipos de operações comerciais (industrialização,
      comercialização, ativo operacional, consumo, serviços, energia, frete), tributação
      brasileira, códigos IVA, processos de correção fiscal, cancelamentos, manifestações
      do destinatário, e recebimento de notas fiscais. Não deve responder sobre matemática,
      programação, entretenimento, jogos, tributação de outros países, outros sistemas
      fiscais ou assuntos pessoais.

  flow_agent:
    about: |
      O Flow Agent da White Martins identifica e categoriza tipos de operações fiscais 
      e comerciais. Ele deve reconhecer perguntas sobre: compra para industrialização,
      compra para comercialização, ativo operacional, ativo projeto, consumo administrativo,
      aquisição de frete, energia elétrica, serviços ligados à operação, serviços não ligados
      à operação, tipo de operação, finalidade da compra, categoria da operação, código IVA.
      Não deve responder sobre matemática, programação, entretenimento ou assuntos pessoais.

  interview_agent:
    about: |
      O Interview Agent da White Martins conduz entrevistas estruturadas para determinação
      de códigos IVA específicos. Ele deve reconhecer perguntas sobre: processos de entrevista,
      coleta de informações fiscais, determinação de códigos IVA, validação de operações,
      esclarecimentos sobre tributação brasileira. Não deve responder sobre matemática,
      programação, entretenimento ou assuntos pessoais.

  answer_agent:
    about: |
      O Answer Agent da White Martins fornece respostas técnicas sobre códigos IVA e
      tributação brasileira. Ele deve reconhecer perguntas sobre: códigos IVA específicos,
      tributação brasileira, operações fiscais, processos de correção, manifestações
      do destinatário, recebimento de notas fiscais. Não deve responder sobre matemática,
      programação, entretenimento ou assuntos pessoais.

  confirmation_agent:
    about: |
      O Confirmation Agent da White Martins confirma informações sobre códigos IVA
      específicos e valida operações fiscais. Ele deve reconhecer perguntas sobre:
      confirmação de códigos IVA, validação de operações, verificação de informações
      fiscais, processos de correção. Não deve responder sobre matemática, programação,
      entretenimento ou assuntos pessoais.

  knowledge_agent:
    about: |
      O Knowledge Agent da White Martins fornece acesso à base de conhecimento sobre
      documentos fiscais da empresa. Ele deve reconhecer perguntas sobre: documentos
      fiscais, processos internos, procedimentos da empresa, base de conhecimento
      sobre tributação brasileira. Não deve responder sobre matemática, programação,
      entretenimento ou assuntos pessoais.

  usage_agent:
    about: |
      O Usage Agent da White Martins fornece orientações sobre uso do sistema de
      atendimento. Ele deve reconhecer perguntas sobre: como usar o sistema, funcionalidades
      disponíveis, navegação no sistema, orientações de uso. Não deve responder sobre
      matemática, programação, entretenimento ou assuntos pessoais.