keywords:
  flow:
    - iva
    - duvida iva
    - duvida sobre iva
    - qual iva
  confirmation:
    - confirmar
    - validação
    - conferência
    - revisar solicitação
  knowledge:
    - procedimento
    - documentação
    - dúvidas gerais
    - norma
  usage:
    - usar o sistema
    - como funciona
    - ajuda plataforma
    - suporte ferramenta
